In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [24]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [26]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [27]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [28]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [29]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [30]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [31]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [33]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('salary_scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [35]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\Piyush Naula\anaconda3\envs\myenv\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [37]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [38]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100588.5078 - mae: 100588.5078 - val_loss: 98564.1875 - val_mae: 98564.1875
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99384.1641 - mae: 99384.1641 - val_loss: 97293.5391 - val_mae: 97293.5391
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 98929.6016 - mae: 98929.6016 - val_loss: 93837.2969 - val_mae: 93837.2969
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 93465.7969 - mae: 93465.7969 - val_loss: 87906.5547 - val_mae: 87906.5547
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88026.3516 - mae: 88026.3516 - val_loss: 79965.6016 - val_mae: 79965.6016
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 78617.1719 - mae: 78617.1719 - val_loss: 71389.1406 - val_mae: 71389.1406
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 70472.3203 - mae: 70472.3203 - val_loss: 63523.3750 - val_mae: 63523.3750
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 62861.3203 - mae: 62861.3203 - val_loss: 57476.8398 - val_mae: 57476.8398
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 56835.4062 - mae: 56835.4062 - val_loss: 53650.8945 - val_mae: 53650.8945
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 53810.3203 - mae: 53810.3203 - val_loss: 51761.4141 - val_mae: 51761.4141
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 51468.3945 - mae: 51468.3945 - val_loss: 51057.0156 - val_mae: 51057.0156
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51544.6016 - mae: 51544.6016 - val_loss: 50835.8594 - val_mae: 50835.8594
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50752.5273 - mae: 50752.5273 - val_loss: 50760.5234 - val_mae: 50760.5234
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50623.7812 - mae: 50623.7812 - val_loss: 50726.9023 - val_mae: 50726.9023
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49762.3594 - mae: 49762.3594 - val_loss: 50690.4141 - val_mae: 50690.4141
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50480.7617 - mae: 50480.7617 - val_loss: 50651.2266 - val_mae: 50651.2266
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50243.8164 - mae: 50243.8164 - val_loss: 50621.7852 - val_mae: 50621.7852
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50579.2383 - mae: 50579.2383 - val_loss: 50598.4531 - val_mae: 50598.4531
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49576.5000 - mae: 49576.5000 - val_loss: 50564.8281 - val_mae: 50564.8281
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50387.2266 - mae: 50387.2266 - val_loss: 50543.4805 - val_mae: 50543.4805
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49830.2891 - mae: 49830.2891 - val_loss: 50520.8828 - val_mae: 50520.8828
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50594.0781 - mae: 50594.0781 - val_loss: 50502.1094 - val_mae: 50502.1094
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49361.4258 - mae: 49361.4258 - val_loss: 50475.2812 - val_mae: 50475.2812
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50322.2188 - mae: 50322.2188 - val_loss: 50454.2539 - val_mae: 50454.2539
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50856.4727 - mae: 50856.4727 - val_loss: 50436.3594 - val_mae: 50436.3594
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50098.3203 - mae: 50098.3203 - val_loss: 50436.1328 - val_mae: 50436.1328
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49759.0547 - mae: 49759.0547 - val_loss: 50413.6406 - val_mae: 50413.6406
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49930.4336 - mae: 49930.4336 - val_loss: 50409.0391 - val_mae: 50409.0391
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49869.6016 - mae: 49869.6016 - val_loss: 50396.7031 - val_mae: 50396.7031
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50162.9766 - mae: 50162.9766 - val_loss: 50388.0156 - val_mae: 50388.0156
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49840.5469 - mae: 49840.5469 - val_loss: 50383.5039 - val_mae: 50383.5039
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49270.0664 - mae: 49270.0664 - val_loss: 50377.6016 - val_mae: 50377.6016
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49938.0117 - mae: 49938.0117 - val_loss: 50369.8008 - val_mae: 50369.8008
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49377.5859 - mae: 49377.5859 - val_loss: 50366.2695 - val_mae: 50366.2695
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50411.2031 - mae: 50411.2031 - val_loss: 50362.1055 - val_mae: 50362.1055
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49633.1523 - mae: 49633.1523 - val_loss: 50366.2812 - val_mae: 50366.2812
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49898.0312 - mae: 49898.0312 - val_loss: 50359.6914 - val_mae: 50359.6914
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49204.2461 - mae: 49204.2461 - val_loss: 50354.2695 - val_mae: 50354.2695
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49057.6797 - mae: 49057.6797 - val_loss: 50355.2734 - val_mae: 50355.2734
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49585.5938 - mae: 49585.5938 - val_loss: 50343.1016 - val_mae: 50343.1016
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49558.9766 - mae: 49558.9766 - val_loss: 50336.9141 - val_mae: 50336.9141
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49700.3945 - mae: 49700.3945 - val_loss: 50337.1328 - val_mae: 50337.1328
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50076.0078 - mae: 50076.0078 - val_loss: 50334.4453 - val_mae: 50334.4453
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49853.4727 - mae: 49853.4727 - val_loss: 50329.4648 - val_mae: 50329.4648
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49622.2539 - mae: 49622.2539 - val_loss: 50329.1719 - val_mae: 50329.1719
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49206.9102 - mae: 49206.9102 - val_loss: 50334.7656 - val_mae: 50334.7656
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 48999.8711 - mae: 48999.8711 - val_loss: 50335.9609 - val_mae: 50335.9609
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49132.4883 - mae: 49132.4883 - val_loss: 50334.6836 - val_mae: 50334.6836
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49459.9688 - mae: 49459.9688 - val_loss: 50341.4453 - val_mae: 50341.4453
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 48848.1914 - mae: 48848.1914 - val_loss: 50345.9883 - val_mae: 50345.9883
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49843.1641 - mae: 49843.1641 - val_loss: 50342.9102 - val_mae: 50342.9102
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49015.6797 - mae: 49015.6797 - val_loss: 50337.5273 - val_mae: 50337.5273
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49279.6172 - mae: 49279.6172 - val_loss: 50336.0391 - val_mae: 50336.0391
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49301.0703 - mae: 49301.0703 - val_loss: 50331.7188 - val_mae: 50331.7188
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49767.1289 - mae: 49767.1289 - val_loss: 50327.7031 - val_mae: 50327.7031
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49863.1133 - mae: 49863.1133 - val_loss: 50332.3203 - val_mae: 50332.3203
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49288.6328 - mae: 49288.6328 - val_loss: 50325.3594 - val_mae: 50325.3594
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49225.9492 - mae: 49225.9492 - val_loss: 50342.5664 - val_mae: 50342.5664
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49390.9961 - mae: 49390.9961 - val_loss: 50343.7930 - val_mae: 50343.7930
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49235.8125 - mae: 49235.8125 - val_loss: 50348.6016 - val_mae: 50348.6016
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49332.5703 - mae: 49332.5703 - val_loss: 50341.1836 - val_mae: 50341.1836
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49335.3828 - mae: 49335.3828 - val_loss: 50347.8789 - val_mae: 50347.8789
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49299.6016 - mae: 49299.6016 - val_loss: 50345.8008 - val_mae: 50345.8008
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49794.2266 - mae: 49794.2266 - val_loss: 50335.3359 - val_mae: 50335.3359
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 48904.4141 - mae: 48904.4141 - val_loss: 50342.4062 - val_mae: 50342.4062
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49970.7383 - mae: 49970.7383 - val_loss: 50354.0156 - val_mae: 50354.0156
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49033.5508 - mae: 49033.5508 - val_loss: 50364.3633 - val_mae: 50364.3633

In [39]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [40]:
%tensorboard --logdir regressionlogs/fit/20250423-170843

Reusing TensorBoard on port 6009 (pid 460), started 0:25:32 ago. (Use '!kill 460' to kill it.)

In [41]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

 1/63 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 58214.3906 - mae: 58214.3906

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 51238.4453 - mae: 51238.4453
Test MAE : 50325.359375

In [42]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.